apiVersion: v1
kind: Service
metadata:
  name: rag-ai-service
spec:
  selector:
    app: rag-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: NodePort # Espone l'app su una porta del tuo PC